### ISSUE TITLE
Vitals weight and height can´t be recorded if my local settings are diffent than USA

### ISSUE THREAD

**Issue by guatesuper** [openemr/openemr#6303] opened 2023-03-23 23:27 UTC
### Describe the bug
I can´t save weight in pounds or kg, or height in inches or centimeters if I don´t set English(standard) as my language when logging in.
I am testing Spanish (Latin America)
The function convInputElement inside vitals.js in line 77 is trying to save value instead of convValue.

### To Reproduce
Login with Spanish (Latin America) as language, then go to "Paciente" in top menu, then you have to click on Búsqueda, then select any patient, then select any encounter, then you select Clinico and then Vitales (to set a vital signs assessment), then when you type any weight or height, you get in the console "Failed to get valid number for input with id  weight_input_usa  with value  <number you typed>" 
![image](https://user-images.githubusercontent.com/60876703/227385833-1b883bca-e230-4389-995d-10a99443ea81.png)

### Expected behavior

Let you input weight or height and convert it to US or metrics.

### Client configuration

- Browser: Firefox 110.0
- OpenEMR version: 7.0.1-dev
- Operating system: Ubuntu 22.04

**Comment by adunsulag** [comment] 2023-03-29 14:43
This is a duplicate of #6292.  I'm working on a fix now.

**Closed** 2023-03-29 19:36 UTC
