### ISSUE TITLE
Move away from Bower

### ISSUE THREAD

**Issue by OzairP** [openemr/openemr#1600] opened 2018-05-04 01:08 UTC
Bower is deprecated, need to move over to `npm`

https://bower.io/blog/

**Comment by bradymiller** [comment] 2018-05-04 05:34
Hi @OzairP ,
It's great to see somebody interested in this stuff. The bower "project" in openemr was started to centralize and organize assets (prior to this, they were scattered all over the database). Would be great to migrate away from bower; is this something you are willing to help us with. Here's the wiki page that tracks the bower "project":
https://www.open-emr.org/wiki/index.php/Bower
thanks,
-brady

**Comment by bradymiller** [comment] 2018-05-12 18:41
per 5/12/18 conference call, will go to npm
(and confirmed during conference call that npm can support different directories, and different versions of same package)

**Comment by sjpadgett** [comment] 2018-05-12 18:52
And run script.

**Comment by bradymiller** [comment] 2018-05-12 19:02
just so I don't forget:
I am planning to slowly look into this with @d3sandoval functioning as an advisor(this is why we are both assigned to this). If anybody else wishes to take this on, though, I would be happy to oblige :)

**Comment by d3sandoval** [comment] 2018-05-12 21:01
Assuming that packages like jQuery and qtip are the reasons why we can't have just one version of a package? https://github.com/openemr/openemr/tree/master/public/assets

I've used this package to install specific versions and custom directories: https://github.com/scott113341/npm-install-version

This matches our use-case better than's yarn's alias feature: https://mobile.twitter.com/sebmck/status/873958247304232961 (which is what i'd recommend if we had a similar requirement in a "js across the stack" app).

**Comment by robertdown** [comment] 2018-05-12 21:38
Interesting @d3sandoval. Would love to drop multi-version requirements and simplify our vendor tree

**Comment by MatthewVita** [comment] 2018-05-16 04:14
Super excited for npm!

**Comment by robertdown** [comment] 2018-05-16 16:16
In the past we've basically `grep'd` the code looking for the files that _do_ use an old version, bump it and manually test. It's exhausting, but we don't have proper UI testing at the moment. 🤷‍♂️

**Comment by bradymiller** [comment] 2018-05-16 22:59
yep, elbow grease :)
Here's on ongoing issue to deal with jquery which is where most of the duplicate versions are associated with:
https://github.com/openemr/openemr/issues/842

**Comment by bradymiller** [comment] 2018-05-21 00:19
Sounds great (agree to get in 1651 in first, though):
Regarding committing vendor code, for the bower stuff, would be a good idea until we have a robust, production build strategy worked out.

**Comment by bradymiller** [comment] 2018-06-26 06:01
hi @kofiav ,
@d3sandoval is working on this (he's working on migrating all front-end components to npm and incorporating a build step into the openemr packages); very exciting stuff.
-brady

**Comment by bradymiller** [comment] 2018-06-26 06:02
@kofiav ,
For now to get your stuff working, feel free to use npm and then we can can incorporate it into the final solution by @d3sandoval in the future.

**Comment by d3sandoval** [comment] 2018-06-26 15:17
I won't get a chance to look at this closely until late next week at the earliest. In order to not block this contribution, I'll agree with @bradymiller here and recommend using your own package.json for the time being. In addressing #1600 , we will have one package.json in the root directory to install all frontend dependencies.

**Comment by kofiav** [comment] 2018-06-26 15:23
@d3sandoval 

No worries, there is no rush on my end. I'm glad someone is looking at this. I was having troubles dealing with Bower so I was happy to find that someone had already started an issue and there's already a lot of progress moving to alternatives (npm).

**Comment by bradymiller** [comment] 2018-09-17 08:05
done

**Closed by bradymiller** 2018-09-17 08:05 UTC
