### ISSUE TITLE
Bug found and fixed in procedures edit (openemr duplicates `Ordered Procedures` )

### ISSUE THREAD

**Issue by A1Gard** [openemr/openemr#501] opened 2017-02-28 11:40 UTC
When we try to edit procedure in `Encounter` it Duplicates all Ordered Procedures after any edit by mistake.

![duplicate1](https://cloud.githubusercontent.com/assets/9222481/23403647/4d91a09c-fdc6-11e6-9783-64e6880eb73a.png)

The reason is Join not complete and read duplicate from `procedure_order_code`,Really need find common column between `procedure_order_code` and `procedure_type`, to fix it I add one column with this query:
```
ALTER TABLE `procedure_order_code`
	ADD COLUMN `procedure_id` INT UNSIGNED NULL AFTER `procedure_order_title`;
```
then edit  forms/procedure_order/new.php for edit and insert action:

```
sqlBeginTrans();
      $procedure_order_seq = sqlQuery( "SELECT IFNULL(MAX(procedure_order_seq),0) + 1 AS increment FROM procedure_order_code WHERE procedure_order_id = ? ", array($formid));
      $poseq = sqlInsert("INSERT INTO procedure_order_code SET ".
      "procedure_order_id = ?, " .
      "diagnoses = ?, " .
      "procedure_order_title = ?, " . 
      "procedure_id = ?, " . // add this line with $_POST['form_proc_type'][$i] in passed problems
      "procedure_code = (SELECT procedure_code FROM procedure_type WHERE procedure_type_id = ?), " .
      "procedure_name = (SELECT name FROM procedure_type WHERE procedure_type_id = ?)," .
      "procedure_order_seq = ? ",
      array($formid, strip_escape_custom($_POST['form_proc_type_diag'][$i]), strip_escape_custom($_POST['form_proc_order_title'][$i]),$_POST['form_proc_type'][$i], $ptid, $ptid, $procedure_order_seq['increment']));
      sqlCommitTrans();
```
and view.php in that folder for view action:
```

$opres = sqlStatement("SELECT " .
      "pc.procedure_order_seq, pc.procedure_code, pc.procedure_name, " .
      "pc.diagnoses,pc.procedure_order_title, pt.procedure_type_id " .
      "FROM procedure_order_code AS pc " .
      "LEFT JOIN procedure_type AS pt ON pt.lab_id = ? AND " .
      "pt.procedure_code = pc.procedure_code " .
      "WHERE pc.procedure_order_id = ? ". 
      "AND pc.procedure_id = pt.procedure_type_id " . // add this condition 
      "ORDER BY pc.procedure_order_seq",
      array($row['lab_id'], $formid));
    while ($oprow = sqlFetchArray($opres)) {
```

And this bug fixed. This issue is report bug and the solution to how fix it.

Another image sample: 
![duplicate2](https://cloud.githubusercontent.com/assets/9222481/23403648/4d95688a-fdc6-11e6-9a25-430c16cd1df0.png)

Thanks for openemr  developing. 
sorry for my bad English

**Comment by bradymiller** [comment] 2017-03-01 09:29
Hi @A1Gard ,
Thanks for this report. Anyway you could submit a pull request with the code changes?
@sunsetsystems (ie. the procedures guru :) ), any thoughts on this issue?
-brady

**Comment by sunsetsystems** [comment] 2017-03-01 16:47
Surely this would have been noticed before, so I guess I don't understand. Could you list specific steps to see the problem from a fresh installation? Also please indicate which OpenEMR release. Thanks.

**Comment by juggernautsei** [comment] 2017-03-02 10:55
Rod,
I have seen this issue since 4.2.0. The first time I built out the lab feature to connect to an outside lab. NOT that connecting to the outside lab causes this. The issue is random. There is not rhythm to it. Just out of the blue it seems to randomly pick procedure and generate these entries on edit. The version I am reporting is 4.2.2.

**Comment by sunsetsystems** [comment] 2017-03-02 11:09
OK thanks, I'll try to reproduce the problem and see if it's really necessary to modify the database.

**Comment by juggernautsei** [comment] 2017-03-02 11:35
I followed the code above and it does fix a problem but causes a problem. When applying the fix, past entries can no long be retrieved.

**Comment by sunsetsystems** [comment] 2017-03-02 19:00
I think the underlying problem here is that for a particular lab, the lab's order code (procedure_type.procedure_code) is expected to be unique regardless of the procedure type. This seems like a reasonable expectation, however it's not enforced.

Complicating this though is that there is an "activity" flag in the procedure_type table that is not checked when joining with it. So perhaps there are some duplicate procedure codes that are marked inactive? I'm not even sure offhand what would mark one as inactive.

Anyway, please check your procedure_type table for duplicate procedure_code values with the same lab_id. Let me know if you find any, and what the reason for them might be.

**Comment by juggernautsei** [comment] 2017-03-02 19:31
Rod, 
you are right on the money. In the chart, there are two procedure orders done on the same day.  So the system is expecting a single order per encounter (like most of the system). But the provider is entering multiple orders on the same patient because he needs on order to go to one lab and the second order to go to a different lab.

**Comment by sunsetsystems** [comment] 2017-03-02 19:34
As a minor correction, procedure_type should always be "ord" for a procedure order code. So the query should check for that because it could be that a result code in the compendium duplicates an order code. I'll work up a fix but I need some feedback on my previous comment to make sure we deal with the problem(s) at hand.

**Comment by sunsetsystems** [comment] 2017-03-02 19:40
Sherwin I think either you or I do not understand. It should be fine to have multiple orders in an encounter, or multiple procedures in an order. What I need you to do is check for duplicate procedure_code values in your procedure_type table (the compendium).

**Comment by sunsetsystems** [comment] 2017-03-02 20:34
Here's a revised query to replace the second one mentioned by A1Gard. Please let me know if this works. No other changes should be needed.

`    $opres = sqlStatement("SELECT " .
      "pc.procedure_order_seq, pc.procedure_code, pc.procedure_name, " .
      "pc.diagnoses, pc.procedure_order_title, " .
      // In case of duplicate procedure codes this gets just one.
      "(SELECT pt.procedure_type_id FROM procedure_type AS pt WHERE " .
      "pt.procedure_type LIKE 'ord%' AND pt.lab_id = ? AND " .
      "pt.procedure_code = pc.procedure_code ORDER BY " .
      "pt.activity DESC, pt.procedure_type_id LIMIT 1) AS procedure_type_id " .
      "FROM procedure_order_code AS pc " .
      "WHERE pc.procedure_order_id = ? " .
      "ORDER BY pc.procedure_order_seq",
      array($row['lab_id'], $formid));
    while ($oprow = sqlFetchArray($opres)) {
      $oparr[] = $oprow;
    }
`

**Comment by sunsetsystems** [comment] 2017-03-02 20:38
Please try the following to replace the second query mentioned by A1Gard and let me know if it works. No other changes should be needed.

```
    $opres = sqlStatement("SELECT " .
      "pc.procedure_order_seq, pc.procedure_code, pc.procedure_name, " .
      "pc.diagnoses, pc.procedure_order_title, " .
      // In case of duplicate procedure codes this gets just one.
      "(SELECT pt.procedure_type_id FROM procedure_type AS pt WHERE " .
      "pt.procedure_type LIKE 'ord%' AND pt.lab_id = ? AND " .
      "pt.procedure_code = pc.procedure_code ORDER BY " .
      "pt.activity DESC, pt.procedure_type_id LIMIT 1) AS procedure_type_id " .
      "FROM procedure_order_code AS pc " .
      "WHERE pc.procedure_order_id = ? " .
      "ORDER BY pc.procedure_order_seq",
      array($row['lab_id'], $formid));
    while ($oprow = sqlFetchArray($opres)) {
      $oparr[] = $oprow;
    }
```

**Comment by juggernautsei** [comment] 2017-03-02 22:34
That fixed the problem. Now each order shows only one entry.

**Comment by sunsetsystems** [comment] 2017-03-02 23:19
Thanks Sherwin. I'll give A1Gard a chance to test also, and will plan to push the fix tomorrow.

**Comment by juggernautsei** [comment] 2017-03-03 10:37
To answer your earlier question about the procedure_type.procedure_code. In that table there are duplicate numbers in that table. 
![procedure_code](https://cloud.githubusercontent.com/assets/834958/23547986/6d3d5d5a-ffd3-11e6-8d58-96dc9427222c.png)

**Comment by sunsetsystems** [comment] 2017-03-03 16:48
OK.  I have pushed this fix to the upstream master. Thanks to A1Gard for identifying the cause of the problem.

**Comment by sunsetsystems** [comment] 2017-03-03 22:04
Closing this since it seems to be handled.

**Closed by sunsetsystems** 2017-03-03 22:04 UTC
Labels: Bug

**Comment by bradymiller** [comment] 2017-03-03 23:35
fyi,
I will place this fix in the next 5.0.0 patch.

**Comment by A1Gard** [comment] 2017-03-04 06:21
@bradymiller I'm trying to develop openemr for Persian people since about 6 months ago and I feel that it's awesome. and I can help to develop openemr eagerly. I found some bugs before and fixed it.
@sunsetsystems I  checked your fixed code and It is OK.

kind regards

**Comment by bradymiller** [comment] 2017-03-04 09:05
@A1Gard Thanks! Definitely post your prior bug fixes and looking forward to your development.
As an aside, have you ever tried to convert the Calendar to a Persian Calendar (we occasionally get that request)?

**Comment by A1Gard** [comment] 2017-03-04 18:33
@bradymiller It's possible, but need time to analyze the system and try to develop.
The reason:
1. System have many jQuery It's make conflict to persian calendar's jquery plugin.
2. some calendar page  is look like smarty but Its not smarty ,not php certainly, `ajax_calander` files for days , weeks and months.

Give me times to analyze this.
