### ISSUE TITLE
Issue with medical_problem api

### ISSUE THREAD

**Issue by srp-pawar** [openemr/openemr#6988] opened 2023-11-07 05:07 UTC
### Describe the bug
Response error while getting request to all the medical_problem api endpoint.
OpenEMR v-7.0.1 stable release
### To Reproduce

1)add medical problem using UI and getting the list of medical problems using any tool(like postman) the response is 500 internal server error without any response body.(api- apis/default/api/medical_problem)

2) clear all the medical_problems data that had been added using UI 
3)using postman tool creating a request to post medical problem using the api endpoint(apis/default/api/patient/{puuid}/medical_problem) the response recieved is 201 created 

4)And send a request to get the medical problems (api- apis/default/api/medical_problem) then we get 200 OK response with response body.
1. Add a '....'

### Expected behavior
200 OK Response using UI as well as API endpoint

###screenshots 
1)response when medical_problem is added using UI 
![image](https://github.com/openemr/openemr/assets/82868470/f2f695a4-f7fb-4750-a969-b34e716195cd)

2) response when medical_problem is added using api endpoint
![image](https://github.com/openemr/openemr/assets/82868470/91fe2b19-dc56-45a9-be2a-fa05d4031474)

### Client configuration

- Browser: Chrome
- OpenEMR version: 7.0.1
- Operating system: Windows
- Installation  : Docker Image

**Comment by adunsulag** [comment] 2023-11-09 02:17
@srp-pawar can you provide what data you are entering in for the medical problem?  Are you able to reproduce this on the demo environments? I just went and entered a number of medical problems and haven't been able to see the 500 errors you are seeing. https://www.open-emr.org/wiki/index.php/Development_7.0.1_Demo

**Comment by srp-pawar** [comment] 2023-11-09 04:46
Sure **@adunsulag** 

The main issue is when we are adding **Medical_records**  using **UI-FORMS** and when we fetch the records using API endpoint i.e 
**(apis/default/api/medical_problem)** using this api then we will get this 500 internal Server error.

To reproduce this issue I will provide the link please check it once. 
[link to Video](https://www.canva.com/design/DAFzpN3PV7M/BOSvUGEmsUs5iNHplmi2wA/watch?utm_content=DAFzpN3PV7M&utm_campaign=designshare&utm_medium=link&utm_source=editor)

Note: 
1) OpenEMR is running on Docker Container port: 8001 and the request is sent to the same port using the postman.


below is the configuration for Docker image (copied from openEMR/Devops): 

> version: '3.1'
services:
  mysql:
    restart: always
    image: mariadb:10.11
    command: [ 'mysqld', '--character-set-server=utf8mb4' ]
    volumes:
      - databasevolume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
  openemr:
    restart: always
    image: openemr/openemr:7.0.1
    ports:
      - 8001:80
      - 443:443
    volumes:
      - logvolume01:/var/log
      - sitevolume:/var/www/localhost/htdocs/openemr/sites
    environment:
      MYSQL_HOST: mysql
      MYSQL_ROOT_PASS: root
      MYSQL_USER: openemr
      MYSQL_PASS: openemr
      OE_USER: admin
      OE_PASS: pass
    depends_on:
      - mysql
volumes:
  logvolume01: {}
  sitevolume: {}
  databasevolume: {}

**Comment by srp-pawar** [comment] 2023-11-09 05:10
And one more thing I tried the same thing in the given [environment] (https://ten.openemr.io/b/openemr)
and here are the [logs] (https://ten.openemr.io/log/logPhp.txt)

> [09-Nov-2023 04:56:10 UTC] [2023-11-09T04:56:10.798213+00:00] OpenEMR.ERROR: dispatch.php failed token verify for resource {"resource":"/default/api/patient"} []
[09-Nov-2023 04:58:29 UTC] [2023-11-09T04:58:29.041533+00:00] OpenEMR.ERROR: HttpRestRouteHandler::dispatch() failed to encode JSON objectMalformed UTF-8 characters, possibly incorrectly encoded {"clientId":"lXbvp18UM0Ib27aaq-AWKG5oyKN7GQCrZzimUjFKUug","userUUID":"9a909be9-9d7b-4bbb-8a76-f74d6937e993","userType":"users","path":"{}"} []
[09-Nov-2023 05:01:18 UTC] [2023-11-09T05:01:18.019921+00:00] OpenEMR.ERROR: HttpRestRouteHandler::dispatch() failed to encode JSON objectMalformed UTF-8 characters, possibly incorrectly encoded {"clientId":"lXbvp18UM0Ib27aaq-AWKG5oyKN7GQCrZzimUjFKUug","userUUID":"9a909be9-9d7b-4bbb-8a76-f74d6937e993","userType":"users","path":"{}"} []
[09-Nov-2023 05:04:15 UTC] [2023-11-09T05:04:15.348637+00:00] OpenEMR.ERROR: HttpRestRouteHandler::dispatch() failed to encode JSON objectMalformed UTF-8 characters, possibly incorrectly encoded {"clientId":"lXbvp18UM0Ib27aaq-AWKG5oyKN7GQCrZzimUjFKUug","userUUID":"9a909be9-9d7b-4bbb-8a76-f74d6937e993","userType":"users","path":"{}"} []

Note Environment and logs are in the same link you have provided 
![image](https://github.com/openemr/openemr/assets/82868470/348d0a17-63c0-46e9-b5e7-75d1fa92d1f1)

**Comment by adunsulag** [comment] 2023-11-14 15:55
@srp-pawar I was able to reproduce the issue on the 7.0.1 demo machines following the video you provided.  Thank you.  It looks like this issue has been fixed in the latest development release which is why I was unable to reproduce the problem.  You can verify this for yourself by using one of the development demos against the master release branch here: https://www.open-emr.org/wiki/index.php/Development_Demo

If you can try one of those development environments and let me know if you continue to have problems that would be helpful.  The 7.0.2 release is slated to go out this week which should have this problem fixed for you.  Please let me know if you continue to have issues.

**Comment by adunsulag** [comment] 2023-11-15 21:55
Marking this as closed and fixed in 7.0.2.

**Closed by adunsulag** 2023-11-15 21:55 UTC
Labels: Bug, Status: Can't Reproduce
