### ISSUE TITLE
fees->payment bug

### ISSUE THREAD

**Issue by stephenwaite** [openemr/openemr#1055] opened 2017-08-28 16:49 UTC
hi @sjpadgett @juggernautsei can reproduce bug by:

1. select a pt with past encounters, a balance due and no encounter dated today
2. verify total due from main pt screen by expanding billing widget (should be a pt balance due and a total due)
3. choose fees->payment and notice top line in payment entry table (it has no encounter # and this is where the disappearing payment is entered)

![untitled](https://user-images.githubusercontent.com/5618372/29783853-dff249d4-8bef-11e7-8957-b03053eb11b8.png)

4. choose credit card as the payment method and invoice balance as the payment against
5. then put an amount in the Paying box on that line and click save

**Comment by juggernautsei** [comment] 2017-08-28 18:28
That is excellent detective work, Sir Sherlock.

**Comment by sjpadgett** [comment] 2017-08-28 18:31
See what you mean and payment probably should still show up in ledger but maybe as a patient payment/unapplied or something along those lines. Use to be, I thought, an encounter create option would open to allow applying payment.
I'm not sure any longer how reconciliation happens. I'm guessing for encounter billing it is front payment and/or checkout!

**Comment by juggernautsei** [comment] 2017-08-28 18:41
About the new billing module. Is there a preview around? Is it going to do away with what is currently being used? Is there any info on the new billing suite?

**Comment by stephenwaite** [comment] 2017-08-28 20:53
no, Jerry's working on the 837I and cleaning up any errors we find along the way in the current billing module

**Comment by stephenwaite** [comment] 2017-08-31 10:50
@juggernautsei maybe you were referring to @visolve-openemr 's billing module http://live.visolve.com/pbm/web/login ?

**Comment by juggernautsei** [comment] 2017-08-31 12:45
Nope. Didn't know that existed.

**Comment by bradymiller** [comment] 2018-01-11 21:31
@stephenwaite ,
Is this still a bug in most recent codebase?
-brady

**Comment by juggernautsei** [comment] 2018-01-11 23:01
No, I think this works well. Had to explain to the staff that could no longer use the blank space at the top when patient walk in to make a payment without an appointment. I had to explain to use any previous encounter to enter the amount against and the biller would sort out the rest.

**Comment by bradymiller** [comment] 2018-01-11 23:04
Great. Then will close this issue.

**Closed by bradymiller** 2018-01-11 23:04 UTC

**Comment by sjpadgett** [comment] 2018-01-11 23:35
note: I fixed this behavior along with validations in front payment. The disappearing payments were pre payments and was caused by problems in patient ledger and validation in front payments. You can not make a payment against a todays encounter if encounter does not exist yet or patient does not have an appointment. Making a payment against past encounters for a today encounter is a bad idea and pre payments now work correctly and I believe this fix was back ported to v5.0.0 so this issue kicked off several PR's.

**Comment by juggernautsei** [comment] 2018-01-12 11:55
@stephenwaite  Glad, you said something because it totally slipped my mind about the pre-payment option. I have sent an email to the office to update them on taking in prepayments.
