### ISSUE TITLE
PDF not generated from Patient summary screen - Report

### ISSUE THREAD

**Issue by arnabnaha** [openemr/openemr#487] opened 2017-02-20 13:59 UTC
Hi,
I am on development version of openemr 5.0.1 and on windows. I was seeing my patients and when tried to print the patient summary report pdf from patient summary screen -> Report ->download PDF, it gave me a white page. On checking the error log i saw this - 

[Mon Feb 20 19:11:46.643383 2017] [:error] [pid 6776:tid 1868] [client 117.194.193.159:52988] PHP Fatal error:  Uncaught exception 'Exception' with message 'TCPDF ERROR: Some data has already been output, can't send PDF file' in C:\\xampp\\htdocs\\openemr\\library\\html2pdf\\vendor\\tecnickcom\\tcpdf\\tcpdf.php:2927\nStack trace:\n#0 C:\\xampp\\htdocs\\openemr\\library\\html2pdf\\vendor\\tecnickcom\\tcpdf\\tcpdf.php(7620): TCPDF->Error('Some data has a...')\n#1 C:\\xampp\\htdocs\\openemr\\library\\html2pdf\\html2pdf.class.php(395): TCPDF->Output('report.pdf', 'I')\n#2 C:\\xampp\\htdocs\\openemr\\interface\\patient_file\\report\\custom_report.php(804): HTML2PDF->Output('report.pdf', 'I')\n#3 {main}\n  thrown in C:\\xampp\\htdocs\\openemr\\library\\html2pdf\\vendor\\tecnickcom\\tcpdf\\tcpdf.php on line 2927, referer: http://nahahealthclinic.no-ip.org/openemr/interface/patient_file/report/patient_report.php

Please help!

**Comment by bradymiller** [comment] 2017-02-21 07:02
@arnabnaha ,
Are you noting this happening with a specific note/form, or is it always happening?

**Comment by arnabnaha** [comment] 2017-02-21 07:06
No..its always happening...it gives me a total white page whenever i try pdf, even without selecting any forms. For printing the demographics also, it shows a white page

**Comment by arnabnaha** [comment] 2017-02-21 07:09
This happens even in the openemr 5.0.0 demo in wiki

**Comment by bradymiller** [comment] 2017-02-21 09:20
Bug confirmed and assigned high priority.

**Comment by bradymiller** [comment] 2017-02-22 01:49
Just committed a fix for this (was secondary to evil white space).
Tested well. Let me know if it didn't work for you.
I'll plan to place this fix in the next 5.0.0 patch (which will be pretty soon since this is a critical feature)

**Comment by bradymiller** [comment] 2017-02-22 01:50
btw, here's the fix:
https://github.com/openemr/openemr/commit/a40fdbe42dafb1c98e500974fa3313b3ba145ccc

**Comment by arnabnaha** [comment] 2017-02-23 14:47
Still not working - Here is the new php error

[Thu Feb 23 20:15:01.293888 2017] [:error] [pid 3992:tid 1928] [client 117.194.194.4:51659] PHP Fatal error:  Uncaught <span style="color: #AA0000; font-weight: bold;">\nERROR n\xc2\xb04</span><br>\nFile : C:\\xampp\\htdocs\\openemr\\library\\html2pdf\\_class\\parsingHtml.class.php<br>\nLine : 118<br>\n<br>\nHTML code invalid, the tags are not closed in an orderly fashion.<br>Status : <pre>Array\n(\n    [0] => div\n    [1] => div\n    [2] => div\n    [3] => div\n    [4] => table\n    [5] => tr\n    [6] => td\n)\n</pre>\n<br><br>HTML : ...Round and Reactive&lt;br /&gt;      &lt;/tr&gt;\n    &lt;/table&gt;\n        &lt;br /&gt;...\n  thrown in C:\\xampp\\htdocs\\openemr\\library\\html2pdf\\_class\\parsingHtml.class.php on line 118, referer: http://nahahealthclinic.no-ip.org/openemr/interface/patient_file/report/patient_report.php

**Comment by arnabnaha** [comment] 2017-02-23 15:43
the bug also persists in openemr 5.0.0 official demo

**Comment by bradymiller** [comment] 2017-02-23 17:40
This appears to be a possible form issue.
Do you get the issue when you don't select any forms?
If it is a form issue, can you localize which form it is?
(as an aside, the 5.0.0 demo won't be fixed until the patch is released)

**Comment by sunsetsystems** [comment] 2017-02-23 18:16
Right, likely to be specific to some form. The message means the html2pdf library doesn't like the generated HTML.

Also, you can just omit the closing "?>" at the end of a script to avoid the trailing white space problem. PHP will auto-generate it.

**Comment by arnabnaha** [comment] 2017-02-24 04:54
Hi...
This is working..actually few of my forms are made from xmlformgen...I recreated those forms and the pdf got displayed. I have another issue of pdf getting cropped. I am creating a new issue for that. Thanks for the help.

**Closed** 2017-02-24 07:48 UTC
Labels: Bug, Priority: Blocking
