### ISSUE TITLE
Encounter menu causes loss of functionality

### ISSUE THREAD

**Issue by arnabnaha** [openemr/openemr#701] opened 2017-05-03 16:43 UTC
Hi

1st..
The width of the encounter menu is huge. This leads to non visibility of the upper part of the forms. need to fix the visibility part.
![issue1](https://cloud.githubusercontent.com/assets/1074948/25671217/beeea10a-304c-11e7-852b-c4edc364a01d.jpg)

2nd. 
few forms like the history form and the followup form created with xmlformgen are not opening but other forms of xmlformgen are opening well. This might be because, I have grouped the other forms under a category called Examination whereas the history form is sole form under category "history" and followup form is sole form under category "follow Up". Even the Track Anything form kept under category "Track Form" is not opening. See Pic

![issue2](https://cloud.githubusercontent.com/assets/1074948/25671448/b692e56a-304d-11e7-9b1e-4fb158cb5a33.jpg)

Hope you will help

**Comment by robertdown** [comment] 2017-05-03 17:04
Thanks for reporting this, I'll look into it. It appears that the issue is related to how many top level menu items you have in the menu. I didn't account for so many. I'll look into a solution

**Comment by arnabnaha** [comment] 2017-05-03 17:05
Thanks @robertdown

**Comment by bradymiller** [comment] 2017-05-06 22:47
Another issue on this is the Fee Sheet link is no longer showing in the Administrative Menu.

**Comment by bradymiller** [comment] 2017-05-06 23:00
Another issue is the Fee Sheet (get to it by clicking on the top menu) styling looks much worse(things look crammed together and out fo place).

Another issue is the Care Plan link in Clinical is missing (this combined with the missing fee sheet item makes me think there is a bug where you are skipping the first item).

(note I removed browser cache prior to this testing)

**Comment by bradymiller** [comment] 2017-05-06 23:05
Another issue. The menu does not work in the Procedure Order form (can see it but clicking on it does nothing).

Another issue. The Delete Encounter only opens correct popup when looking at encounter. If click if from the forms it throws and error: 
``````
Not Found

The requested URL /openemr/interface/patient_file/encounter/toggledivs(this.id, this.id) was not found on this server.

**Comment by robertdown** [comment] 2017-05-07 03:57
Several of these issues have been solved

**Comment by robertdown** [comment] 2017-05-07 05:01
This was getting difficult to track so I split all the issues into separate bugs. Closing this one

**Closed by robertdown** 2017-05-07 05:01 UTC
Labels: Bug
