### ISSUE TITLE
Token API CORS error when client secret is used to authorize

### ISSUE THREAD

**Issue by Shramana-Biswas** [openemr/openemr#6598] opened 2023-06-22 06:29 UTC
### Token API CORS error when client secret is used to authorize

write concise description of what the bug is.
App is registered as confidential single Patient Application, and on passing client secret during authorization the token API is returning CORS error.

### To Reproduce

1. App clientType = Confidential & Single Patient Application
2. Got ClientId and Client secret after registration
3. When passing client secret to authorize, the token API call is throwing CORS issue

<img width="413" alt="Screenshot 2023-06-22 115531" src="https://github.com/openemr/openemr/assets/135021985/98750052-bcb1-47c6-8aa2-016192702cbc">

### Expected behavior
Token API is return access token successfully

### Client configuration

- Browser: Chrome
- OpenEMR version: OpenEMR 7.0.1

**Comment by adunsulag** [comment] 2023-06-23 14:33
Duplicate of #6497 and already fixed in master.

**Closed by adunsulag** 2023-06-23 14:33 UTC
