### ISSUE TITLE
Demographics Error: two windows opened, tabbed mode

### ISSUE THREAD

**Issue by ophthal** [openemr/openemr#409] opened 2016-12-30 18:00 UTC
When trying to save an email address (or another demographic field), I am getting the following type of error:

`Internal error: Attempt to change patient data with pid = '874' when current pid is '1445' for id '875'`

This may only happen when two separate windows are opened with different patient info in each.  Using the error example above, there are two windows opened, one with pid="1445" and the other pid="874".  The error occurs when changing demographics in the window with pid="874", whereas the second window with pid="1445", works fine.    In the "874 window", despite the patient panel showing the info for pid=874, the demographics tab thinks the pid is 1445 and thus the error is generated. 

Switching to framed mode and all works fine.

**Comment by bradymiller** [comment] 2016-12-30 20:34
In OpenEMR, should not be able to work on 2 different patient's at the same time. This is why certain windows get closed (in both framed and tab user interfaces) when close or change a patient. What steps allowed you to open 2 separate patient windows?

**Comment by bradymiller** [comment] 2016-12-30 20:35
To clarify when discussing windows. Do you mean completely different logins?

**Comment by sunsetsystems** [comment] 2016-12-30 20:55
As the message indicates, this error indicates an internal problem.  The javascript function restoreSession() is supposed to be called just before opening any new window or otherwise making a context-sensitive request to the web server.  It sounds like there's a case when using tabs that this is not happening... so yes, it's important to know exactly what steps are needed to see this error.

**Comment by ophthal** [comment] 2016-12-30 21:56
You can have multiple patient windows open at the same time.  That is how the Flow Board works (open new patient in a new window).  I will often have more than one patient opened at once.  I thought that is what restoreSession() allowed/handled.  If you navigate visits or forms in any of these patient windows they work fine.  I noticed this problem with demographics, and maybe adding a new prescription.  On one occasion I printed a prescription and another patient's info was printed in the PDF.  I had no idea why and could not reproduce it, but this is probably the same bug since "Edit prescriptions" (which leads to Add Prescription) is on this demographics page.  I'll test it now.

**Comment by ophthal** [comment] 2016-12-30 22:24
Note, there is no Logout/Login between patient windows.

I could not duplicate the Add Prescription problem.  
I did duplicate the problem with "Edit Medical Problems", then add a new one.   The new Problem showed up in the other patient's chart.
Adding a new Allergy worked fine for each patient.
I did duplicate the problem with "Edit Medications", then add a new one.   The new med showed up in the other patient's chart.  On refresh, the other patient's medication list was displayed under the current patient listed in the "patient Panel".
So this is a bit of a mess.  I am not sure where the problem is.

Maybe if the Flow Board "open new patient in new window" always opens to a NAMED window, we can stop this?  The next patient would open in the NAMED window, replacing the current contents of NAMED window.  A user can still use the original flow board window to navigate to Calendar and open a new patient chart in the first window.  Maybe we are just missing a restoreSession() somewhere.  I really do not know...

**Comment by sunsetsystems** [comment] 2016-12-31 00:15
Try something like this:

1. Open patient 1.
2. Open a new window with patient 2.
3. Open patient 1's demographics edit form and change some field but do not save yet.
4. Do something with patient 2 that involves a request to the web server.
5. Save patient 1's form.

If you are able to reproduce an error, document the steps exactly.  Also indicate which browser/version you are using.

Demographics is good here because the save logic has the "sanity check" that caused the error message you mentioned.  But other places where data are saved may also have issues.  Reliably reproducing just one problem will go a long way towards finding multiple errors of the same type.

**Comment by bradymiller** [comment] 2016-12-31 03:05
Hi,

The way I usually test this is opening 1 instance of OpenEMR in English and then another instance of OpenEMR in another language (such as Dutch). Then I click link in 1 instance, then the other instance, and so on; and it is obvious if the language changes that the link was not protected with restoreSession()

Doing this, I noted that the tab ui refresh icon was not protected, so I just brought in that fix:
https://github.com/openemr/openemr/commit/79c525490808a289e9c2766fc3918de72dcebb91

There is also weirdness happening when do a login/logout (it sometimes kills other sessions when this is done).

-brady

**Comment by bradymiller** [comment] 2016-12-31 03:23
btw @ophthal , you are correct in assuming that the flow board "open new patient in new window" is the same as a separate login (it is given a unique session id) and is protected by the restoreSession() calls.

**Comment by bradymiller** [comment] 2016-12-31 03:35
Just brought in fixes that should address @ophthal bug reports above in the Issues:
https://github.com/openemr/openemr/commit/ce76ff2737a04d9a43abd10494a35d22e3675ad6

**Comment by ophthal** [comment] 2016-12-31 14:01
http://openemr.sourceforge.net/wiki/index.php/Administration_Globals says:
 Open Demographics in New Window from Patient Flow Board

        **This setting was removed in OpenEMR 5.0.0**
        (This setting was added in OpenEMR version 4.2.1)
        See Patient Flow Board

**Comment by sunsetsystems** [comment] 2016-12-31 17:16
Hi Brady, I don't think that will fix it because dlgopen() calls cascwin() which already includes a call to restoreSession().  More testing seems advisable.

**Comment by bradymiller** [comment] 2016-12-31 19:18
@ophthal , the 'Open Demographics in New Window from Patient Flow Board' manual setting in globals was removed and was migrated to a persistent ("auto") setting by MDSupport. So, it basically remembers the setting (per user) and uses that:
https://github.com/openemr/openemr/commit/37a0efa2fa41efba02754e7e2615666a301ea440

**Comment by bradymiller** [comment] 2016-12-31 19:28
@sunsetsystems ,
I tested this and the change did fix it. Prior to the placement of top.restoreSession() , it leaked the other session (via display of  Dutch), and after the placement of top.restoreSession(), it no longer leaked the other session.
(I just reconfirmed this behavior)

Perhaps there is an issue with cascwin()??

**Comment by sunsetsystems** [comment] 2016-12-31 20:34
@bradymiller Oh I see... dialog.js has code that in the tab_mode case replaces the dlgopen function on-the-fly with one that might not call top.restoreSession().  A bit hard to tell what it does as there are no comments at all.  But it appears that is the best place for the fix.

Note dynamic replacement of functions like this leads to confusion.  I don't understand why KY would not have just modified the original dlgopen function to handle the tab case.

**Comment by bradymiller** [comment] 2017-01-01 02:03
@sunsetsystems ,

This fixes the dlgopen that is used by tabs ui (I tested it and it blocks the session leak):
https://github.com/openemr/openemr/pull/413

On a related matter, also incorporated cache clearing for display.js, which I initially planned to bring in for master only(and not rel-500) because of the extensive code changes; however considering the drastic changes in the display.js file which would break if upgraders used old cached version, will bring it into rel-500 also:
https://github.com/openemr/openemr/pull/411

**Comment by sunsetsystems** [comment] 2017-01-01 02:44
Thanks Brady!  That's excellent.

**Comment by bradymiller** [comment] 2017-01-01 08:19
Just brought above PR fixes into the codebase. I am betting the dlgopen fix was @ophthal main issue since that would of allowed a session leak whenever a popup/modal was opened in the tabs ui.

**Comment by ophthal** [comment] 2017-01-01 13:52
Not yet.  @bradymiller to get Dutch in one window, don't you have to change this in Globals and then in the second window login all over again?  There is no logout/login happening here...

Here are the steps to reproduce the error in Firefox:
Login.
There are two patients in the system both with appointments today.
One window is open, Window 1.  
Select patient 1, Edit demographics.  Change License to "TestA".  Save.  No problem.
Click Flow Board.  This opens in a different tab.
Select patient 2.  A new window opens, Window 2. 
Edit demographics, change License to "TestB". Save.  No problem.
Return to Window 1.
Select tab for Patient 1 Demographics.
Edit demographics, Change License to "TestC".  Do NOT Save.
Return to Window 2.
Edit demographics, change License to "TestD". Save.  No problem.
Return to Window 1.
Press Save.  
Internal error: Attempt to change patient data with pid = '2549' when current pid is '2548' for id '2552'.    
Note in my example Patient in Window 1 pid="2549" and Paitent in Window 2 pid="2548".

**Comment by bradymiller** [comment] 2017-01-01 19:31
@ophthal ,
Thanks for the detailed report. I am suspicious that we introduced this bug (ie. missing a critical call to top.restoreSession()) with the new validation code. Will look into this when I get to a computer.

**Comment by ophthal** [comment] 2017-01-01 20:23
Now I understand! You have been doing all this coding in your head without a computer.  We need to get you a computer. It is so much easier that way.

**Comment by bradymiller** [comment] 2017-01-02 01:20
Computers are overrated :)

Confirmed @ophthal's well documented bug and brought the following fix into the codebase(also confirmed the fix worked):
https://github.com/openemr/openemr/commit/0175271a6882532e71527898dfb3ebc0507de8a7

@ophthal, let me know if this fixes your issue.

Turns out the new validation code did remove the top.restoreSession() call, so will check other places where the new validation code was brought in. These are scary bugs (session leaking) since can potentially mince patient records, so will take this as a good kick in the butt to ensure top.restoreSession() is being used on the code reviews.

**Comment by ophthal** [comment] 2017-01-03 21:41
Still happening.

**Comment by ophthal** [comment] 2017-01-03 21:43
The error occurs when Patient 1 in Window 1 has an edit made BUT NOT SAVED yet.  Go to the other window and do what you need, edit and save a demographic change.  Return to Window 1 and press save.  Error occurs.

**Comment by bradymiller** [comment] 2017-01-04 02:32
This is just the bug that keeps on giving :)
On my testing it works sometimes and doesn't work other times. There appears to be a session issue going on when open the first patient window from the patient flow board. My hypothesis is that the include of restoreSession.php needs to happen at top of interface/main/main_screen.php and at top of interface/main/tabs/main.php (otherwise when main_screen.php gets redirected to main.php, it may not use the correct session to fill session info in restoreSession.php).

**Comment by bradymiller** [comment] 2017-01-04 03:08
ok, Have confirmed this bug in both frames/tabs and both firefox/chrome. Appears to be a global issue. Next step is to probably test prior versions.

**Comment by bradymiller** [comment] 2017-01-04 06:52
Getting closer; if I turn off the following setting, then the bug goes away:
Administration->Globals->Security->New Form Validation

**Comment by bradymiller** [comment] 2017-01-04 07:54
Just brought in the fix for this issue:
https://github.com/openemr/openemr/commit/55872bd33812687778c15a55ebe1656ffcc5e958

Along the way, also committed a fix prior to this in the login session manager that was messing the sessions up; ie. when logging in, it was closing other instances down.

There is still 1 more weird session activity to fix. If open several window instances via flow board, sometimes when logging out of 1 of them, it will auto log out on other instances

**Comment by bradymiller** [comment] 2017-01-05 02:11
Just posted a PR to fix the the weird logging out activity:
https://github.com/openemr/openemr/pull/420

Here's an explanation of the fix:
Here are steps to produce the bug:
1. Login to OpenEMR.
2. Go to Patient Flow Board and toggle on Open Patient in New Window.
3. A new window(OpenEMR instance) now opens up.
4. Click to logout of the new OpenEMR instance.

Because of code in library/auth.inc, the following bugs happen:
1. The window of the OpenEMR instance that you clicked to logout
   will go away.
2. The Original window (from step 2 above) will then logout.

This is because the 'opener' javascript variable is linked to the
original instance. The fix is to always set the 'opener' variable
to null in the main script for frames (interface/main/main_screen.php)
and tabs (interface/main/tabs/main.php).

**Comment by bradymiller** [comment] 2017-01-05 02:15
@ophthal , sorry to also hijack this issue with several other session issues(sort of turned into a domino effect :) ). Just let me know if your original bug has been finally squashed with the following fix that is now in the codebase: https://github.com/openemr/openemr/commit/55872bd33812687778c15a55ebe1656ffcc5e958
(if so, then I will close this issue)

**Closed** 2017-01-05 10:01 UTC
Labels: Bug, Priority: Blocking, Tab Layout
