### ISSUE TITLE
Insurance and Pharmacy Address Conflict 5.01

### ISSUE THREAD

**Issue by HITECHPR** [openemr/openemr#1575] opened 2018-04-24 11:24 UTC
Try these two scenarios after Activating WENO in Globals

First Scenario
1) Import some pharmacies (That works fine)
2) Go to Administration->Practice->Insurance Companies and add a Insurance Company.
Insurance Company is Duplicated..

Second Scenario
1) Go to Administration->Practice->Insurance Companies and add a Insurance Company (That works fine)
2) Got to Administration->Globals->Other->WENO Management and import a small town
3) Go back Go to Administration->Practice->Insurance Companies
4) Now go back to Administration->Practice->Pharmacies

Insurance Company is Duplicated AND in Pharmacies one of the Pharmacies has the Insurance Company Address AND is Duplicated.

**Comment by bradymiller** [comment] 2018-04-27 09:15
tagging @juggernautsei on this

**Comment by juggernautsei** [comment] 2018-04-27 09:53
I'll take a look at this and see if I can remember what I did. I know there were some table changes after creating the import that is most likely the issue. I'll find out for sure.

**Comment by bradymiller** [comment] 2019-03-29 16:59
hi @juggernautsei , Just checking if I can close this issue?

**Comment by juggernautsei** [comment] 2019-03-29 18:30
Apologies for not getting back to this but we did fix this in a retrofit to 4.2.x. However, going forward, we have taken this function out of the admin section for now. We are not planning on having a pharmacy import at this time. Unless we come up with a reliable data source that is free. 

The problem is how the pharmacy is being imported and the three tables that data is stored and how the foreign key is accounted for. 

Recommend not to use pharmacy import. There is not a patch or fix for what is currently out there. We are currently revamping the feature to add some improvements. We are hoping to have these improvements in the 5.0.2.

**Closed** 2019-03-29 20:42 UTC
