### ISSUE TITLE
database.sql failed at line 6392

### ISSUE THREAD

**Issue by matrix-amiel** [openemr/openemr#261] opened 2016-09-20 10:22 UTC
Hi.
When I ran this database.sql file from command line  (in xampp on windows) I got it -

mysql -uroot -p openemr_p2 < sql/database.sql
Enter password:
ERROR 1064 (42000) at line 6392: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '----------------------------------------------------------

DROP TABLE IF EXIS' at line 1

mysql -uroot -p openemr_p2 < sql/database.sql
Enter password:
ERROR 1064 (42000) at line 8317: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '--------------------------------------------------------

CREATE TABLE `immuniz' at line 1

and the script failed.

**Comment by ophthal** [comment] 2016-09-20 12:05
Looks like I see an evil apostrophe...

**Comment by bradymiller** [comment] 2016-09-21 06:07
I was able to reproduce this error and fixed it with below fix.
Turns out that can not have '---' for the comment lines. Then need to be '--'. Committed the fix to the main codebase:
https://github.com/openemr/openemr/commit/1425d97d0340601f9c18e5868ba003d0bb5fcbb8

**Closed** 2016-09-21 06:07 UTC
Labels: Bug
